dual_laser_merger_node:
  ros__parameters:
    laser_1_topic: "/scan_left"
    laser_2_topic: "/scan_right"
    merged_scan_topic: "/scan"
    merged_cloud_topic: "/scan_cloud"
    target_frame: "base_link"
    angle_min: -3.141592654
    angle_max: 3.141592654
    angle_increment: 0.006544985
    scan_time: 0.1
    range_min: 0.05
    range_max: 20.0
    use_inf: true
    tolerance: 0.05
    queue_size: 10
    enable_shadow_filter: true
    enable_average_filter: true